[project]
name = "tiktok-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.49.0",
    "yt-dlp>=2025.8.27",
]
